# Generated by Django 2.2.4 on 2020-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauser',
            name='verification_code',
            field=models.IntegerField(null=True),
        ),
    ]
