# Generated by Django 2.2.4 on 2020-09-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adda', '0002_auto_20200901_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='add_user',
            new_name='adda_user',
        ),
    ]
